# Generated by Django 3.1.4 on 2020-12-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconcejo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='file',
            field=models.FileField(default=1, upload_to='archivos/'),
            preserve_default=False,
        ),
    ]
